// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daylogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDayLog = `-- name: CreateDayLog :one
INSERT INTO day_logs (user_id, date, started_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, date, started_at, ended_at, is_recording, total_distance_m, place_count, total_duration_sec, created_at, updated_at
`

type CreateDayLogParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Date      pgtype.Date        `db:"date" json:"date"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) CreateDayLog(ctx context.Context, arg CreateDayLogParams) (DayLog, error) {
	row := q.db.QueryRow(ctx, createDayLog, arg.UserID, arg.Date, arg.StartedAt)
	var i DayLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsRecording,
		&i.TotalDistanceM,
		&i.PlaceCount,
		&i.TotalDurationSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endDayLog = `-- name: EndDayLog :one
UPDATE day_logs
SET ended_at = $2, is_recording = false,
    total_distance_m = $3, place_count = $4, total_duration_sec = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, date, started_at, ended_at, is_recording, total_distance_m, place_count, total_duration_sec, created_at, updated_at
`

type EndDayLogParams struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	EndedAt          pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	TotalDistanceM   pgtype.Float8      `db:"total_distance_m" json:"total_distance_m"`
	PlaceCount       pgtype.Int4        `db:"place_count" json:"place_count"`
	TotalDurationSec pgtype.Int4        `db:"total_duration_sec" json:"total_duration_sec"`
}

func (q *Queries) EndDayLog(ctx context.Context, arg EndDayLogParams) (DayLog, error) {
	row := q.db.QueryRow(ctx, endDayLog,
		arg.ID,
		arg.EndedAt,
		arg.TotalDistanceM,
		arg.PlaceCount,
		arg.TotalDurationSec,
	)
	var i DayLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsRecording,
		&i.TotalDistanceM,
		&i.PlaceCount,
		&i.TotalDurationSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDayLogByID = `-- name: GetDayLogByID :one
SELECT id, user_id, date, started_at, ended_at, is_recording, total_distance_m, place_count, total_duration_sec, created_at, updated_at FROM day_logs WHERE id = $1
`

func (q *Queries) GetDayLogByID(ctx context.Context, id pgtype.UUID) (DayLog, error) {
	row := q.db.QueryRow(ctx, getDayLogByID, id)
	var i DayLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsRecording,
		&i.TotalDistanceM,
		&i.PlaceCount,
		&i.TotalDurationSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDayLogByUserAndDate = `-- name: GetDayLogByUserAndDate :one
SELECT id, user_id, date, started_at, ended_at, is_recording, total_distance_m, place_count, total_duration_sec, created_at, updated_at FROM day_logs WHERE user_id = $1 AND date = $2
`

type GetDayLogByUserAndDateParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetDayLogByUserAndDate(ctx context.Context, arg GetDayLogByUserAndDateParams) (DayLog, error) {
	row := q.db.QueryRow(ctx, getDayLogByUserAndDate, arg.UserID, arg.Date)
	var i DayLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsRecording,
		&i.TotalDistanceM,
		&i.PlaceCount,
		&i.TotalDurationSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDayLogsByUser = `-- name: ListDayLogsByUser :many
SELECT id, user_id, date, started_at, ended_at, is_recording, total_distance_m, place_count, total_duration_sec, created_at, updated_at FROM day_logs
WHERE user_id = $1
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type ListDayLogsByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListDayLogsByUser(ctx context.Context, arg ListDayLogsByUserParams) ([]DayLog, error) {
	rows, err := q.db.Query(ctx, listDayLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DayLog{}
	for rows.Next() {
		var i DayLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.StartedAt,
			&i.EndedAt,
			&i.IsRecording,
			&i.TotalDistanceM,
			&i.PlaceCount,
			&i.TotalDurationSec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
