// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDot = `-- name: CreateDot :one
INSERT INTO dots (day_log_id, user_id, location, latitude, longitude, timestamp, place_name, place_category, memo, emotion)
VALUES (
    $1, $2,
    ST_SetSRID(ST_MakePoint($4, $3), 4326),  -- ST_MakePoint(lng, lat)
    $3, $4,
    $5, $6, $7, $8, $9
)
RETURNING id, day_log_id, user_id, location, latitude, longitude, timestamp, place_name, place_category, photo_url, memo, emotion, created_at
`

type CreateDotParams struct {
	DayLogID      pgtype.UUID        `db:"day_log_id" json:"day_log_id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Latitude      float64            `db:"latitude" json:"latitude"`
	Longitude     float64            `db:"longitude" json:"longitude"`
	Timestamp     pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	PlaceName     pgtype.Text        `db:"place_name" json:"place_name"`
	PlaceCategory pgtype.Text        `db:"place_category" json:"place_category"`
	Memo          pgtype.Text        `db:"memo" json:"memo"`
	Emotion       pgtype.Text        `db:"emotion" json:"emotion"`
}

func (q *Queries) CreateDot(ctx context.Context, arg CreateDotParams) (Dot, error) {
	row := q.db.QueryRow(ctx, createDot,
		arg.DayLogID,
		arg.UserID,
		arg.Latitude,
		arg.Longitude,
		arg.Timestamp,
		arg.PlaceName,
		arg.PlaceCategory,
		arg.Memo,
		arg.Emotion,
	)
	var i Dot
	err := row.Scan(
		&i.ID,
		&i.DayLogID,
		&i.UserID,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Timestamp,
		&i.PlaceName,
		&i.PlaceCategory,
		&i.PhotoUrl,
		&i.Memo,
		&i.Emotion,
		&i.CreatedAt,
	)
	return i, err
}

const getDotsByDayLog = `-- name: GetDotsByDayLog :many
SELECT id, day_log_id, user_id, location, latitude, longitude, timestamp, place_name, place_category, photo_url, memo, emotion, created_at FROM dots
WHERE day_log_id = $1
ORDER BY timestamp ASC
`

func (q *Queries) GetDotsByDayLog(ctx context.Context, dayLogID pgtype.UUID) ([]Dot, error) {
	rows, err := q.db.Query(ctx, getDotsByDayLog, dayLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dot{}
	for rows.Next() {
		var i Dot
		if err := rows.Scan(
			&i.ID,
			&i.DayLogID,
			&i.UserID,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.Timestamp,
			&i.PlaceName,
			&i.PlaceCategory,
			&i.PhotoUrl,
			&i.Memo,
			&i.Emotion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDotsByUserAndDate = `-- name: GetDotsByUserAndDate :many
SELECT d.id, d.day_log_id, d.user_id, d.location, d.latitude, d.longitude, d.timestamp, d.place_name, d.place_category, d.photo_url, d.memo, d.emotion, d.created_at FROM dots d
JOIN day_logs dl ON dl.id = d.day_log_id
WHERE d.user_id = $1 AND dl.date = $2
ORDER BY d.timestamp ASC
`

type GetDotsByUserAndDateParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetDotsByUserAndDate(ctx context.Context, arg GetDotsByUserAndDateParams) ([]Dot, error) {
	rows, err := q.db.Query(ctx, getDotsByUserAndDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dot{}
	for rows.Next() {
		var i Dot
		if err := rows.Scan(
			&i.ID,
			&i.DayLogID,
			&i.UserID,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.Timestamp,
			&i.PlaceName,
			&i.PlaceCategory,
			&i.PhotoUrl,
			&i.Memo,
			&i.Emotion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDotPhotoURL = `-- name: UpdateDotPhotoURL :one
UPDATE dots SET photo_url = $2 WHERE id = $1 RETURNING id, day_log_id, user_id, location, latitude, longitude, timestamp, place_name, place_category, photo_url, memo, emotion, created_at
`

type UpdateDotPhotoURLParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	PhotoUrl pgtype.Text `db:"photo_url" json:"photo_url"`
}

func (q *Queries) UpdateDotPhotoURL(ctx context.Context, arg UpdateDotPhotoURLParams) (Dot, error) {
	row := q.db.QueryRow(ctx, updateDotPhotoURL, arg.ID, arg.PhotoUrl)
	var i Dot
	err := row.Scan(
		&i.ID,
		&i.DayLogID,
		&i.UserID,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.Timestamp,
		&i.PlaceName,
		&i.PlaceCategory,
		&i.PhotoUrl,
		&i.Memo,
		&i.Emotion,
		&i.CreatedAt,
	)
	return i, err
}
