// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DayLog struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	Date             pgtype.Date        `db:"date" json:"date"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt          pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	IsRecording      bool               `db:"is_recording" json:"is_recording"`
	TotalDistanceM   pgtype.Float8      `db:"total_distance_m" json:"total_distance_m"`
	PlaceCount       pgtype.Int4        `db:"place_count" json:"place_count"`
	TotalDurationSec pgtype.Int4        `db:"total_duration_sec" json:"total_duration_sec"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Dot struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	DayLogID      pgtype.UUID        `db:"day_log_id" json:"day_log_id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Location      interface{}        `db:"location" json:"location"`
	Latitude      float64            `db:"latitude" json:"latitude"`
	Longitude     float64            `db:"longitude" json:"longitude"`
	Timestamp     pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	PlaceName     pgtype.Text        `db:"place_name" json:"place_name"`
	PlaceCategory pgtype.Text        `db:"place_category" json:"place_category"`
	PhotoUrl      pgtype.Text        `db:"photo_url" json:"photo_url"`
	Memo          pgtype.Text        `db:"memo" json:"memo"`
	Emotion       pgtype.Text        `db:"emotion" json:"emotion"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Room struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Name          string             `db:"name" json:"name"`
	OwnerID       pgtype.UUID        `db:"owner_id" json:"owner_id"`
	InviteCode    pgtype.Text        `db:"invite_code" json:"invite_code"`
	InviteExpires pgtype.Timestamptz `db:"invite_expires" json:"invite_expires"`
	MaxMembers    int32              `db:"max_members" json:"max_members"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RoomMember struct {
	RoomID   pgtype.UUID        `db:"room_id" json:"room_id"`
	UserID   pgtype.UUID        `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type SharedDayLog struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	RoomID   pgtype.UUID        `db:"room_id" json:"room_id"`
	DayLogID pgtype.UUID        `db:"day_log_id" json:"day_log_id"`
	UserID   pgtype.UUID        `db:"user_id" json:"user_id"`
	SharedAt pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

type User struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	FirebaseUid     string             `db:"firebase_uid" json:"firebase_uid"`
	Provider        string             `db:"provider" json:"provider"`
	Nickname        string             `db:"nickname" json:"nickname"`
	ProfileImage    pgtype.Text        `db:"profile_image" json:"profile_image"`
	CharacterConfig []byte             `db:"character_config" json:"character_config"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
