// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	CreateDayLog(ctx context.Context, arg CreateDayLogParams) (DayLog, error)
	CreateDot(ctx context.Context, arg CreateDotParams) (Dot, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EndDayLog(ctx context.Context, arg EndDayLogParams) (DayLog, error)
	FindEncounters(ctx context.Context, arg FindEncountersParams) ([]FindEncountersRow, error)
	GetDayLogByID(ctx context.Context, id pgtype.UUID) (DayLog, error)
	GetDayLogByUserAndDate(ctx context.Context, arg GetDayLogByUserAndDateParams) (DayLog, error)
	GetDotsByDayLog(ctx context.Context, dayLogID pgtype.UUID) ([]Dot, error)
	GetDotsByUserAndDate(ctx context.Context, arg GetDotsByUserAndDateParams) ([]Dot, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Room, error)
	GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error)
	GetSharedDayLogsByRoomAndDate(ctx context.Context, arg GetSharedDayLogsByRoomAndDateParams) ([]GetSharedDayLogsByRoomAndDateRow, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	ListDayLogsByUser(ctx context.Context, arg ListDayLogsByUserParams) ([]DayLog, error)
	ListRoomsByUser(ctx context.Context, userID pgtype.UUID) ([]Room, error)
	SetInviteCode(ctx context.Context, arg SetInviteCodeParams) (Room, error)
	ShareDayLog(ctx context.Context, arg ShareDayLogParams) (SharedDayLog, error)
	UpdateCharacterConfig(ctx context.Context, arg UpdateCharacterConfigParams) (User, error)
	UpdateDotPhotoURL(ctx context.Context, arg UpdateDotPhotoURLParams) (Dot, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
