// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoomMemberParams struct {
	RoomID pgtype.UUID `db:"room_id" json:"room_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, owner_id) VALUES ($1, $2) RETURNING id, name, owner_id, invite_code, invite_expires, max_members, created_at, updated_at
`

type CreateRoomParams struct {
	Name    string      `db:"name" json:"name"`
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.OwnerID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.InviteExpires,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, owner_id, invite_code, invite_expires, max_members, created_at, updated_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.InviteExpires,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByInviteCode = `-- name: GetRoomByInviteCode :one
SELECT id, name, owner_id, invite_code, invite_expires, max_members, created_at, updated_at FROM rooms WHERE invite_code = $1 AND invite_expires > NOW()
`

func (q *Queries) GetRoomByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByInviteCode, inviteCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.InviteExpires,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomMemberCount = `-- name: GetRoomMemberCount :one
SELECT COUNT(*) FROM room_members WHERE room_id = $1
`

func (q *Queries) GetRoomMemberCount(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRoomMemberCount, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS(SELECT 1 FROM room_members WHERE room_id = $1 AND user_id = $2)
`

type IsRoomMemberParams struct {
	RoomID pgtype.UUID `db:"room_id" json:"room_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRoomsByUser = `-- name: ListRoomsByUser :many
SELECT r.id, r.name, r.owner_id, r.invite_code, r.invite_expires, r.max_members, r.created_at, r.updated_at FROM rooms r
JOIN room_members rm ON rm.room_id = r.id
WHERE rm.user_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) ListRoomsByUser(ctx context.Context, userID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.InviteCode,
			&i.InviteExpires,
			&i.MaxMembers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInviteCode = `-- name: SetInviteCode :one
UPDATE rooms SET invite_code = $2, invite_expires = $3, updated_at = NOW()
WHERE id = $1 RETURNING id, name, owner_id, invite_code, invite_expires, max_members, created_at, updated_at
`

type SetInviteCodeParams struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	InviteCode    pgtype.Text        `db:"invite_code" json:"invite_code"`
	InviteExpires pgtype.Timestamptz `db:"invite_expires" json:"invite_expires"`
}

func (q *Queries) SetInviteCode(ctx context.Context, arg SetInviteCodeParams) (Room, error) {
	row := q.db.QueryRow(ctx, setInviteCode, arg.ID, arg.InviteCode, arg.InviteExpires)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.InviteCode,
		&i.InviteExpires,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
