// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shared.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findEncounters = `-- name: FindEncounters :many
SELECT
    a.id AS dot_a_id,
    b.id AS dot_b_id,
    a.user_id AS user_a,
    b.user_id AS user_b,
    a.timestamp,
    ST_Distance(a.location::geography, b.location::geography) AS distance_m,
    a.latitude AS lat,
    a.longitude AS lng,
    a.place_name
FROM dots a
JOIN dots b ON a.user_id != b.user_id
    AND a.day_log_id IN (
        SELECT sdl.day_log_id FROM shared_day_logs sdl
        JOIN day_logs dl ON dl.id = sdl.day_log_id
        WHERE sdl.room_id = $1 AND dl.date = $2
    )
    AND b.day_log_id IN (
        SELECT sdl.day_log_id FROM shared_day_logs sdl
        JOIN day_logs dl ON dl.id = sdl.day_log_id
        WHERE sdl.room_id = $1 AND dl.date = $2
    )
    AND ABS(EXTRACT(EPOCH FROM (a.timestamp - b.timestamp))) < 1800
    AND ST_DWithin(a.location::geography, b.location::geography, 100)
WHERE a.user_id < b.user_id  -- 중복 방지
ORDER BY a.timestamp
`

type FindEncountersParams struct {
	RoomID pgtype.UUID `db:"room_id" json:"room_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

type FindEncountersRow struct {
	DotAID    pgtype.UUID        `db:"dot_a_id" json:"dot_a_id"`
	DotBID    pgtype.UUID        `db:"dot_b_id" json:"dot_b_id"`
	UserA     pgtype.UUID        `db:"user_a" json:"user_a"`
	UserB     pgtype.UUID        `db:"user_b" json:"user_b"`
	Timestamp pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	DistanceM interface{}        `db:"distance_m" json:"distance_m"`
	Lat       float64            `db:"lat" json:"lat"`
	Lng       float64            `db:"lng" json:"lng"`
	PlaceName pgtype.Text        `db:"place_name" json:"place_name"`
}

func (q *Queries) FindEncounters(ctx context.Context, arg FindEncountersParams) ([]FindEncountersRow, error) {
	rows, err := q.db.Query(ctx, findEncounters, arg.RoomID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEncountersRow{}
	for rows.Next() {
		var i FindEncountersRow
		if err := rows.Scan(
			&i.DotAID,
			&i.DotBID,
			&i.UserA,
			&i.UserB,
			&i.Timestamp,
			&i.DistanceM,
			&i.Lat,
			&i.Lng,
			&i.PlaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedDayLogsByRoomAndDate = `-- name: GetSharedDayLogsByRoomAndDate :many
SELECT sdl.id, sdl.room_id, sdl.day_log_id, sdl.user_id, sdl.shared_at, dl.date, dl.total_distance_m, dl.place_count, dl.total_duration_sec
FROM shared_day_logs sdl
JOIN day_logs dl ON dl.id = sdl.day_log_id
WHERE sdl.room_id = $1 AND dl.date = $2
ORDER BY sdl.shared_at DESC
`

type GetSharedDayLogsByRoomAndDateParams struct {
	RoomID pgtype.UUID `db:"room_id" json:"room_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

type GetSharedDayLogsByRoomAndDateRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	RoomID           pgtype.UUID        `db:"room_id" json:"room_id"`
	DayLogID         pgtype.UUID        `db:"day_log_id" json:"day_log_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	SharedAt         pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
	Date             pgtype.Date        `db:"date" json:"date"`
	TotalDistanceM   pgtype.Float8      `db:"total_distance_m" json:"total_distance_m"`
	PlaceCount       pgtype.Int4        `db:"place_count" json:"place_count"`
	TotalDurationSec pgtype.Int4        `db:"total_duration_sec" json:"total_duration_sec"`
}

func (q *Queries) GetSharedDayLogsByRoomAndDate(ctx context.Context, arg GetSharedDayLogsByRoomAndDateParams) ([]GetSharedDayLogsByRoomAndDateRow, error) {
	rows, err := q.db.Query(ctx, getSharedDayLogsByRoomAndDate, arg.RoomID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharedDayLogsByRoomAndDateRow{}
	for rows.Next() {
		var i GetSharedDayLogsByRoomAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.DayLogID,
			&i.UserID,
			&i.SharedAt,
			&i.Date,
			&i.TotalDistanceM,
			&i.PlaceCount,
			&i.TotalDurationSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareDayLog = `-- name: ShareDayLog :one
INSERT INTO shared_day_logs (room_id, day_log_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, day_log_id) DO NOTHING
RETURNING id, room_id, day_log_id, user_id, shared_at
`

type ShareDayLogParams struct {
	RoomID   pgtype.UUID `db:"room_id" json:"room_id"`
	DayLogID pgtype.UUID `db:"day_log_id" json:"day_log_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ShareDayLog(ctx context.Context, arg ShareDayLogParams) (SharedDayLog, error) {
	row := q.db.QueryRow(ctx, shareDayLog, arg.RoomID, arg.DayLogID, arg.UserID)
	var i SharedDayLog
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DayLogID,
		&i.UserID,
		&i.SharedAt,
	)
	return i, err
}
