// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, provider, nickname, profile_image, character_config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, firebase_uid, provider, nickname, profile_image, character_config, created_at, updated_at
`

type CreateUserParams struct {
	FirebaseUid     string      `db:"firebase_uid" json:"firebase_uid"`
	Provider        string      `db:"provider" json:"provider"`
	Nickname        string      `db:"nickname" json:"nickname"`
	ProfileImage    pgtype.Text `db:"profile_image" json:"profile_image"`
	CharacterConfig []byte      `db:"character_config" json:"character_config"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirebaseUid,
		arg.Provider,
		arg.Nickname,
		arg.ProfileImage,
		arg.CharacterConfig,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Provider,
		&i.Nickname,
		&i.ProfileImage,
		&i.CharacterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, provider, nickname, profile_image, character_config, created_at, updated_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Provider,
		&i.Nickname,
		&i.ProfileImage,
		&i.CharacterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, provider, nickname, profile_image, character_config, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Provider,
		&i.Nickname,
		&i.ProfileImage,
		&i.CharacterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCharacterConfig = `-- name: UpdateCharacterConfig :one
UPDATE users
SET character_config = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, provider, nickname, profile_image, character_config, created_at, updated_at
`

type UpdateCharacterConfigParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	CharacterConfig []byte      `db:"character_config" json:"character_config"`
}

func (q *Queries) UpdateCharacterConfig(ctx context.Context, arg UpdateCharacterConfigParams) (User, error) {
	row := q.db.QueryRow(ctx, updateCharacterConfig, arg.ID, arg.CharacterConfig)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Provider,
		&i.Nickname,
		&i.ProfileImage,
		&i.CharacterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET nickname = $2, profile_image = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, provider, nickname, profile_image, character_config, created_at, updated_at
`

type UpdateUserParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Nickname     string      `db:"nickname" json:"nickname"`
	ProfileImage pgtype.Text `db:"profile_image" json:"profile_image"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Nickname, arg.ProfileImage)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Provider,
		&i.Nickname,
		&i.ProfileImage,
		&i.CharacterConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
